version: 2.1

jobs:
  setup:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run:
          name: Configurar entorno de pruebas
          command: echo "Configurando entorno de pruebas..."

  install_dependencies:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run:
          name: Instalar dependencias
          command: npm install

  run_tests:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run:
          name: Ejecutar pruebas
          command: npm test -- --watchAll=false

  build:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run:
          name: Crear build de producción
          command: npm run build

workflows:
  version: 2

  # Workflow para ejecutar pruebas
  test_workflow:
    jobs:
      - setup
      - install_dependencies:
          requires:
            - setup
      - run_tests:
          requires:
            - install_dependencies

  # Workflow para build de producción
  build_workflow:
    jobs:
      - setup
      - install_dependencies:
          requires:
            - setup
      - run_tests:
          requires:
            - install_dependencies
      - build:
          requires:
            - run_tests